ACTION_DISCRETISATION = 5
ACTION_NOISE = 0.1
BACKTRACK_COEFF = 0.8
BACKTRACK_ITERS = 10
CONJUGATE_GRADIENT_ITERS = 10
DAMPING_COEFF = 0.1
DISCOUNT = 0.99
EPSILON = 0.05
ENTROPY_WEIGHT = 0.2
HIDDEN_SIZE = 30
KL_LIMIT = 0.05

######
ON_POLICY_BATCH_SIZE = 2048
POLICY_DELAY = 2
POLYAK_FACTOR = 0.995
PPO_CLIP_RATIO = 0.2
PPO_EPOCHS = 20
TARGET_ACTION_NOISE = 0.2
TARGET_ACTION_NOISE_CLIP = 0.5
TARGET_UPDATE_INTERVAL = 1000
TRACE_DECAY = 0.97


# Fotis
INTER_NUM = 300

REPLAY_SIZE = 10 * INTER_NUM
OFFLINE_UPDATES = 100
TEST_NUM = 2
ACTION_DURATION = 0.2
TIME_PER_TURN = int(ACTION_DURATION * INTER_NUM ) +2

OFF_POLICY_BATCH_SIZE = 128

UPDATE_INTERVAL = 300
MAX_STEPS = UPDATE_INTERVAL * 2

UPDATE_START = 300
TEST_INTERVAL = 1e3
SAVE_INTERVAL = 300 # for the networks

LEARNING_RATE = 1*1e-3
DECAY = False
EXP_DECAY_LR = 0.5

# Direction Values
ACCEL_RATE = 0.8 * 1e-2

# CONTROL_MODE = "accell_dir"
# CONTROL_MODE = "vel"
CONTROL_MODE = "accel"
REWARD_TYPE = "classic" # classic or penalty