ACTION_DISCRETISATION = 5
ACTION_NOISE = 0.1
BACKTRACK_COEFF = 0.8
BACKTRACK_ITERS = 10
CONJUGATE_GRADIENT_ITERS = 10
DAMPING_COEFF = 0.1
DISCOUNT = 0.99
EPSILON = 0.05
ENTROPY_WEIGHT = 0.2
HIDDEN_SIZE = 30
KL_LIMIT = 0.05

######
ON_POLICY_BATCH_SIZE = 2048
POLICY_DELAY = 2
POLYAK_FACTOR = 0.995
PPO_CLIP_RATIO = 0.2
PPO_EPOCHS = 20
REPLAY_SIZE = 10 * 200
TARGET_ACTION_NOISE = 0.2
TARGET_ACTION_NOISE_CLIP = 0.5
TARGET_UPDATE_INTERVAL = 1000
TRACE_DECAY = 0.97


# Fotis
OFFLINE_UPDATES = 10000
TEST_NUM = 10
ACTION_DURATION = 0.2
TIME_PER_TURN = int(ACTION_DURATION * 200 ) +2

OFF_POLICY_BATCH_SIZE = 128

UPDATE_INTERVAL = 600
MAX_STEPS = UPDATE_INTERVAL * 5

UPDATE_START = 800
TEST_INTERVAL = 1e3
SAVE_INTERVAL = 500 # for the networks

LEARNING_RATE = 1*1e-3
DECAY = False
EXP_DECAY_LR = 0.5

# Direction Values
ACCEL_RATE = 0.8 * 1e-2
# ACCEL_RATE_X = 1e-3
# ACCEL_RATE_Y = 0.2 * 1e-1

# Accel Values
# ACCEL_RATE_X = 1e-2
# ACCEL_RATE_Y = 0.2 * 1e-1

# CONTROL_MODE = "accell_dir"
# CONTROL_MODE = "vel"
CONTROL_MODE = "accel"
REWARD_TYPE = "penalty"